"""
Reference Model for SPEC-001
Generated by Agent 2: Executable Specification Synthesizer
Active Evolved Skills Count: 1
"""
from dataclasses import dataclass
import pytest
from hypothesis import given, strategies as st

import os

# Skill-evolved dynamic parameterization:
MAX_DECELERATION_MPS2 = float(os.getenv("MAX_DECELERATION_MPS2", "9.8"))
MIN_SAFE_TTC_SECONDS = float(os.getenv("MIN_SAFE_TTC_SECONDS", "1.5"))
MIN_SENSOR_CONFIDENCE = float(os.getenv("MIN_SENSOR_CONFIDENCE", "0.80"))


class SensorConfidenceError(Exception):
    """Raised when sensor confidence degrades below autonomous operation limits."""
    pass


@dataclass(frozen=True)
class VehicleState:
    time_to_collision: float
    sensor_confidence: float


@dataclass(frozen=True)
class BrakingDecision:
    initiate_deceleration: bool
    target_deceleration: float
    manual_override: bool


def evaluate_braking_policy(state: VehicleState) -> BrakingDecision:
    assert state.time_to_collision >= 0.0, "Time-to-collision cannot be negative."
    assert 0.0 <= state.sensor_confidence <= 1.0, "Sensor confidence must be normalized between 0.0 and 1.0."

    # Clause: CLS-002
    if state.sensor_confidence < MIN_SENSOR_CONFIDENCE:
        return BrakingDecision(
            initiate_deceleration=False,
            target_deceleration=0.0,
            manual_override=True,
        )

    # Clause: CLS-001
    if state.time_to_collision < MIN_SAFE_TTC_SECONDS:
        decision = BrakingDecision(
            initiate_deceleration=True,
            target_deceleration=MAX_DECELERATION_MPS2,
            manual_override=False,
        )
    else:
        decision = BrakingDecision(
            initiate_deceleration=False,
            target_deceleration=0.0,
            manual_override=False,
        )

    # Clause: CLS-003
    assert decision.target_deceleration <= MAX_DECELERATION_MPS2, "Invariant violation: Deceleration exceeded dry pavement limit."
    return decision


# Clause: CLS-003
@given(
    ttc=st.floats(min_value=0.0, max_value=10.0),
    confidence=st.floats(min_value=0.0, max_value=1.0)
)
def test_deceleration_never_exceeds_physical_limit(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert 0.0 <= decision.target_deceleration <= MAX_DECELERATION_MPS2


# Clause: CLS-001
@given(
    ttc=st.floats(min_value=0.0, max_value=MIN_SAFE_TTC_SECONDS - 0.01),
    confidence=st.floats(min_value=MIN_SENSOR_CONFIDENCE, max_value=1.0)
)
def test_emergency_braking_triggers_when_safe_and_confident(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert decision.initiate_deceleration is True
    assert decision.target_deceleration == MAX_DECELERATION_MPS2
    assert decision.manual_override is False


# Clause: CLS-002
@given(
    ttc=st.floats(min_value=0.0, max_value=10.0),
    confidence=st.floats(min_value=0.0, max_value=MIN_SENSOR_CONFIDENCE - 0.01)
)
def test_graceful_degradation_to_manual_override_under_low_confidence(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert decision.manual_override is True
    assert decision.initiate_deceleration is False
