import argparse
import os
import subprocess
import sys
from pathlib import Path


def load_active_skills(repo_root: Path) -> list[str]:
    """Loads evolved skill directives generated by Agent 3."""
    skills_dir = repo_root / "agent_configs" / "skills"
    if not skills_dir.exists():
        return []
    
    directives = []
    for skill_file in skills_dir.glob("*.md"):
        content = skill_file.read_text(encoding="utf-8").strip()
        directives.append(content)
    return directives


def _generate_spec_001_model(spec_id: str, skills: list[str]) -> str:
    """Braking deceleration policy model for Spec-001 (specs/SPEC-001.md)."""
    use_parameterized_boundaries = any("parameterize undefined boundaries" in s.lower() for s in skills)

    boundary_config = """
import os

# Skill-evolved dynamic parameterization:
MAX_DECELERATION_MPS2 = float(os.getenv("MAX_DECELERATION_MPS2", "9.8"))
MIN_SAFE_TTC_SECONDS = float(os.getenv("MIN_SAFE_TTC_SECONDS", "1.5"))
MIN_SENSOR_CONFIDENCE = float(os.getenv("MIN_SENSOR_CONFIDENCE", "0.80"))
""" if use_parameterized_boundaries else """
MAX_DECELERATION_MPS2 = 9.8
MIN_SAFE_TTC_SECONDS = 1.5
MIN_SENSOR_CONFIDENCE = 0.80
"""

    return f'''"""
Reference Model for {spec_id}
Generated by Agent 2: Executable Specification Synthesizer
Active Evolved Skills Count: {len(skills)}
"""
from dataclasses import dataclass
import pytest
from hypothesis import given, strategies as st
{boundary_config}

class SensorConfidenceError(Exception):
    """Raised when sensor confidence degrades below autonomous operation limits."""
    pass


@dataclass(frozen=True)
class VehicleState:
    time_to_collision: float
    sensor_confidence: float


@dataclass(frozen=True)
class BrakingDecision:
    initiate_deceleration: bool
    target_deceleration: float
    manual_override: bool


def evaluate_braking_policy(state: VehicleState) -> BrakingDecision:
    assert state.time_to_collision >= 0.0, "Time-to-collision cannot be negative."
    assert 0.0 <= state.sensor_confidence <= 1.0, "Sensor confidence must be normalized between 0.0 and 1.0."

    # Clause: CLS-002
    if state.sensor_confidence < MIN_SENSOR_CONFIDENCE:
        return BrakingDecision(
            initiate_deceleration=False,
            target_deceleration=0.0,
            manual_override=True,
        )

    # Clause: CLS-001
    if state.time_to_collision < MIN_SAFE_TTC_SECONDS:
        decision = BrakingDecision(
            initiate_deceleration=True,
            target_deceleration=MAX_DECELERATION_MPS2,
            manual_override=False,
        )
    else:
        decision = BrakingDecision(
            initiate_deceleration=False,
            target_deceleration=0.0,
            manual_override=False,
        )

    # Clause: CLS-003
    assert decision.target_deceleration <= MAX_DECELERATION_MPS2, "Invariant violation: Deceleration exceeded dry pavement limit."
    return decision


# Clause: CLS-003
@given(
    ttc=st.floats(min_value=0.0, max_value=10.0),
    confidence=st.floats(min_value=0.0, max_value=1.0)
)
def test_deceleration_never_exceeds_physical_limit(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert 0.0 <= decision.target_deceleration <= MAX_DECELERATION_MPS2


# Clause: CLS-001
@given(
    ttc=st.floats(min_value=0.0, max_value=MIN_SAFE_TTC_SECONDS - 0.01),
    confidence=st.floats(min_value=MIN_SENSOR_CONFIDENCE, max_value=1.0)
)
def test_emergency_braking_triggers_when_safe_and_confident(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert decision.initiate_deceleration is True
    assert decision.target_deceleration == MAX_DECELERATION_MPS2
    assert decision.manual_override is False


# Clause: CLS-002
@given(
    ttc=st.floats(min_value=0.0, max_value=10.0),
    confidence=st.floats(min_value=0.0, max_value=MIN_SENSOR_CONFIDENCE - 0.01)
)
def test_graceful_degradation_to_manual_override_under_low_confidence(ttc: float, confidence: float):
    state = VehicleState(time_to_collision=ttc, sensor_confidence=confidence)
    decision = evaluate_braking_policy(state)
    assert decision.manual_override is True
    assert decision.initiate_deceleration is False
'''


def _generate_spec_002_model(spec_id: str, skills: list[str]) -> str:
    """Battery thermal throttling policy model for Spec-002 (specs/SPEC-002.md)."""
    use_parameterized_boundaries = any("parameterize undefined boundaries" in s.lower() for s in skills)

    boundary_config = """
import os

# Skill-evolved dynamic parameterization:
COOLING_ACTIVATION_TEMP_C = float(os.getenv("COOLING_ACTIVATION_TEMP_C", "45.0"))
MIN_COOLANT_FLOW_LPM = float(os.getenv("MIN_COOLANT_FLOW_LPM", "2.0"))
POWER_THROTTLE_FRACTION = float(os.getenv("POWER_THROTTLE_FRACTION", "0.5"))
MAX_CELL_TEMP_C = float(os.getenv("MAX_CELL_TEMP_C", "60.0"))
""" if use_parameterized_boundaries else """
COOLING_ACTIVATION_TEMP_C = 45.0
MIN_COOLANT_FLOW_LPM = 2.0
POWER_THROTTLE_FRACTION = 0.5
MAX_CELL_TEMP_C = 60.0
"""

    return f'''"""
Reference Model for {spec_id}
Generated by Agent 2: Executable Specification Synthesizer
Active Evolved Skills Count: {len(skills)}
"""
from dataclasses import dataclass
import pytest
from hypothesis import given, strategies as st
{boundary_config}

@dataclass(frozen=True)
class BatteryState:
    cell_temperature_c: float
    coolant_flow_lpm: float


@dataclass(frozen=True)
class ThermalDecision:
    activate_liquid_cooling: bool
    power_throttle_fraction: float


def evaluate_thermal_policy(state: BatteryState) -> ThermalDecision:
    assert state.cell_temperature_c >= -273.15, "Cell temperature cannot be below absolute zero."
    assert state.coolant_flow_lpm >= 0.0, "Coolant flow rate cannot be negative."

    # Clause: CLS-001
    activate_cooling = state.cell_temperature_c > COOLING_ACTIVATION_TEMP_C

    # Clause: CLS-002
    throttle_fraction = POWER_THROTTLE_FRACTION if state.coolant_flow_lpm < MIN_COOLANT_FLOW_LPM else 0.0

    decision = ThermalDecision(
        activate_liquid_cooling=activate_cooling,
        power_throttle_fraction=throttle_fraction,
    )

    # Clause: CLS-003
    assert decision.activate_liquid_cooling or state.cell_temperature_c <= COOLING_ACTIVATION_TEMP_C, \\
        "Invariant violation: Cell above activation threshold without cooling engaged."
    return decision


# Clause: CLS-001
@given(
    cell_temperature_c=st.floats(min_value=-40.0, max_value=MAX_CELL_TEMP_C),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=10.0)
)
def test_cooling_activates_above_threshold_temperature(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.activate_liquid_cooling == (cell_temperature_c > COOLING_ACTIVATION_TEMP_C)


# Clause: CLS-002
@given(
    cell_temperature_c=st.floats(min_value=-40.0, max_value=MAX_CELL_TEMP_C),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=MIN_COOLANT_FLOW_LPM - 0.01)
)
def test_power_throttles_when_coolant_flow_low(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.power_throttle_fraction == POWER_THROTTLE_FRACTION


# Clause: CLS-003
@given(
    cell_temperature_c=st.floats(min_value=COOLING_ACTIVATION_TEMP_C, max_value=MAX_CELL_TEMP_C, exclude_min=True),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=10.0)
)
def test_cooling_engages_before_absolute_maximum_reached(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.activate_liquid_cooling is True
'''


# Registry of known specs Agent 2 can synthesize a reference model for. There is
# no general-purpose NL-to-formal-model synthesis here (that is the Hermes Agent
# runtime's job in the full loop) -- each entry is a hand-verified template tied
# to one spec's actual clauses, so a spec without an entry must fail loudly
# rather than silently reuse an unrelated model under the wrong spec_id.
_MODEL_GENERATORS = {
    "SPEC-001": _generate_spec_001_model,
    "SPEC-002": _generate_spec_002_model,
}


def generate_reference_model_code(spec_id: str, skills: list[str]) -> str:
    """
    Synthesizes the executable reference model for spec_id. If boundary
    enforcement skills are present, boundaries are parameterized via
    environment variables rather than hardcoded constants.
    """
    generator = _MODEL_GENERATORS.get(spec_id)
    if generator is None:
        raise ValueError(
            f"Agent 2 has no synthesis template for '{spec_id}'. Refusing to "
            f"generate a reference model, since reusing another spec's template "
            f"would silently produce an unrelated, mislabeled model. Add a "
            f"template to _MODEL_GENERATORS in agent_2_harness.py for this spec."
        )
    return generator(spec_id, skills)


def run_agent_2(spec_id: str, repo_root: Path) -> Path:
    target_dir = repo_root / "formalizations" / spec_id
    target_dir.mkdir(parents=True, exist_ok=True)
    model_path = target_dir / "reference_model.py"

    # Dynamically load skills evolved by Agent 3
    active_skills = load_active_skills(repo_root)
    if active_skills:
        print(f"[Agent 2] Ingested {len(active_skills)} evolved skill directive(s).")

    code = generate_reference_model_code(spec_id, active_skills)
    model_path.write_text(code, encoding="utf-8")

    result = subprocess.run(
        [sys.executable, "-m", "pytest", str(model_path)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Synthesized reference model failed dynamic verification tests:\n{result.stderr}\n{result.stdout}"
        )

    return model_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Agent 2: Executable Spec Synthesizer Harness")
    parser.add_argument("--spec-id", type=str, required=True, help="ID of the specification")
    parser.add_argument("--repo-root", type=str, default=".", help="Root of repository")
    args = parser.parse_args()

    out_file = run_agent_2(args.spec_id, Path(args.repo_root))
    print(f"[Agent 2] Synthesized and verified formal model at: {out_file}")
