"""
Reference Model for SPEC-002
Generated by Agent 2: Executable Specification Synthesizer
Active Evolved Skills Count: 1
"""
from dataclasses import dataclass
import pytest
from hypothesis import given, strategies as st

import os

# Skill-evolved dynamic parameterization:
COOLING_ACTIVATION_TEMP_C = float(os.getenv("COOLING_ACTIVATION_TEMP_C", "45.0"))
MIN_COOLANT_FLOW_LPM = float(os.getenv("MIN_COOLANT_FLOW_LPM", "2.0"))
POWER_THROTTLE_FRACTION = float(os.getenv("POWER_THROTTLE_FRACTION", "0.5"))
MAX_CELL_TEMP_C = float(os.getenv("MAX_CELL_TEMP_C", "60.0"))


@dataclass(frozen=True)
class BatteryState:
    cell_temperature_c: float
    coolant_flow_lpm: float


@dataclass(frozen=True)
class ThermalDecision:
    activate_liquid_cooling: bool
    power_throttle_fraction: float


def evaluate_thermal_policy(state: BatteryState) -> ThermalDecision:
    assert state.cell_temperature_c >= -273.15, "Cell temperature cannot be below absolute zero."
    assert state.coolant_flow_lpm >= 0.0, "Coolant flow rate cannot be negative."

    # Clause: CLS-001
    activate_cooling = state.cell_temperature_c > COOLING_ACTIVATION_TEMP_C

    # Clause: CLS-002
    throttle_fraction = POWER_THROTTLE_FRACTION if state.coolant_flow_lpm < MIN_COOLANT_FLOW_LPM else 0.0

    decision = ThermalDecision(
        activate_liquid_cooling=activate_cooling,
        power_throttle_fraction=throttle_fraction,
    )

    # Clause: CLS-003
    assert decision.activate_liquid_cooling or state.cell_temperature_c <= COOLING_ACTIVATION_TEMP_C, \
        "Invariant violation: Cell above activation threshold without cooling engaged."
    return decision


# Clause: CLS-001
@given(
    cell_temperature_c=st.floats(min_value=-40.0, max_value=MAX_CELL_TEMP_C),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=10.0)
)
def test_cooling_activates_above_threshold_temperature(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.activate_liquid_cooling == (cell_temperature_c > COOLING_ACTIVATION_TEMP_C)


# Clause: CLS-002
@given(
    cell_temperature_c=st.floats(min_value=-40.0, max_value=MAX_CELL_TEMP_C),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=MIN_COOLANT_FLOW_LPM - 0.01)
)
def test_power_throttles_when_coolant_flow_low(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.power_throttle_fraction == POWER_THROTTLE_FRACTION


# Clause: CLS-003
@given(
    cell_temperature_c=st.floats(min_value=COOLING_ACTIVATION_TEMP_C, max_value=MAX_CELL_TEMP_C, exclude_min=True),
    coolant_flow_lpm=st.floats(min_value=0.0, max_value=10.0)
)
def test_cooling_engages_before_absolute_maximum_reached(cell_temperature_c: float, coolant_flow_lpm: float):
    state = BatteryState(cell_temperature_c=cell_temperature_c, coolant_flow_lpm=coolant_flow_lpm)
    decision = evaluate_thermal_policy(state)
    assert decision.activate_liquid_cooling is True
